apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: balfazaju-python 
  janus-idp.io/tekton: balfazaju-python
  backstage.io/kubernetes-id: balfazaju-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: balfazaju-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml