apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: balfazaju-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/chetna14manku_org/rhtap-qe-python:github-c44afc17e8df418bb7dc7a85e250354ca1fdf086
          name: container-image
